### ISSUE TITLE
Flaskでクライアントからデータを受け取る

### ISSUE THREAD

**Issue by akakou** [give-me-15-min/Judgment#6]
FlaskでクライアントからPOSTでデータを受け取る

### 参考
* https://qiita.com/Sekky0905/items/dff3d0da059d6f5bfabf
* http://conta.hatenablog.com/entry/2013/02/06/162829 (Python2 系)
* https://qiita.com/naoko_s/items/04d68998cfdbe9c1b5f2

**Comment by Tiger1422** [comment]
Done
