### ISSUE TITLE
FlaskでJSONの受け取りをする。

### ISSUE THREAD

**Issue by akakou** [give-me-15-min/Judgment#7]
FlaskでPOSTでJSONを受け取り、その内容を表示すること。

### ヒント・参考にすべき文献
* テストにはrequestsでJSONをPOSTするプログラムの用意が必要。
    * https://qiita.com/hththt/items/14bfc2bf23192b020371
* Flaskの文献。
    * http://conta.hatenablog.com/entry/2013/02/06/162829

### データの例
```
{
    "secret": "this_is_secret_key"
    "target": "this_is_target"
}
```

**Comment by Tiger1422** [comment]
Done
